web:
    image: 'plexinc/pms-docker:latest'
    container_name: plex
    net: host
    environment:
        TZ: 'America/New_York' 
        PLEX_CLAIM: 'claim-YGxyy6Nz61QvaBs6oxpC'
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    volumes:
      - '/mnt/main_hdd/srv/plex/config:/config'
      - '/mnt/main_hdd/srv/plex/transcode:/transcode'
      - '/mnt/main_hdd/media:/data'