version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./build:./run
      - ./build/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: npm_default
      POSTGRES_DB: npm_template_test