version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url "http://gitlab.example.com"
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8081:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/mnt/main_hdd/srv/gitlab/config:/etc/gitlab'
      - '/mnt/main_hdd/srv/gitlab/logs:/var/log/gitlab'
      - '/mnt/main_hdd/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    network_mode: bridge
