web:
    image: 'portainer/portainer:latest'
    container_name: portainer
    restart: always
    hostname: 'portainer.localhost.com'
    ports:
    - '9000:9000'
    - '8000:8000'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - 'portainer_data:/data portainer/portainer'