web:
    image: 'linuxserver/transmission:latest'
    # hostname: '192.168.1.10'
    container_name: transmission
    environment:
        TZ: 'America/New_York'
        PGID: '1000'
        PUID: '1000'
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    volumes:
      - '/mnt/main_hdd/srv/transmission/config:/config'
      - '/mnt/main_hdd/media/incoming:/downloads'
      - '/mnt/main_hdd/media/incoming:/watch'
    network_mode: bridge